name: PHP Lint

on:
  workflow_call:

jobs:
  lint-pr:
    name: Lint on changed files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get changed PHP files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **.php

      - name: Setting up PHP
        if: steps.changed-files.outputs.all_changed_files != ''
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: phpstan, nunomaduro/phpinsights, phpunit, parallel-lint
          extensions: mbstring, simplexml
        env:
          COMPOSER_ALLOW_PLUGINS: dealerdirect/phpcodesniffer-composer-installer

      # - name: Running PHPStan
      #   if: steps.changed-files.outputs.all_changed_files != ''
      #   run: |
      #     echo "Analisando os seguintes arquivos com PHPStan:"
      #     echo "${{ steps.changed-files.outputs.all_changed_files }}"
      #     phpstan analyse ${{ steps.changed-files.outputs.all_changed_files }} --level 7 --error-format=github --no-progress

      # - name: PHP Insights
      #   if: steps.changed-files.outputs.all_changed_files != ''
      #   run: |
      #     phpinsights analyse ${{ steps.changed-files.outputs.all_changed_files }} --no-interaction --min-quality=90 --min-complexity=90 --min-architecture=90 --min-style=90

      - name: PHP Paralel Lint
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          parallel-lint ${{ steps.changed-files.outputs.all_changed_files }} --exclude .git --exclude app --exclude vendor
