name: Secret Scan
on:
  workflow_call:  
    inputs:
      actor:
        required: true
        type: string
  
jobs:
  run-secret-scan:
    runs-on: ubuntu-latest
    name: secret-scan
    steps:
    - run: echo "Checking for secrets. Started by ${{ inputs.actor }}"
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main